site_name: IAI's Python 入门指南
copyright: Copyright &copy; 2024 BUAA IAISU

theme:
  name: material
  language: zh
  # font:
  #   text: Noto Serif SC
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - content.tooltips
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  custom_dir: overrides

repo_url: https://github.com/BobYue-01/python-guide
repo_name: python-guide
edit_uri: edit/master/docs/

nav:
  - 主页: index.md
  - 教程:
    - guide/index.md
    - Day 0：部署环境: guide/0-env.md
    - Day 1：内置类型: guide/1-stdtypes.md
    - Day 2：流程控制: guide/2-flow.md
    - Day 3：面向对象: guide/3-oop.md
  - 文档:
    - doc/index.md
    - 部署环境:
      - doc/env/index.md
      - 了解终端: doc/env/terminal.md
      - 安装解释器: doc/env/interpreter.md
      - 配置包管理器: doc/env/package-manager.md
      - 选择并配置 IDE:
        - doc/env/ide/index.md
        - 配置 VSCode: doc/env/ide/vscode.md
        - 配置 PyCharm: doc/env/ide/pycharm.md
    - 基本语法:
      - doc/syntax/index.md
      - 内置类型: doc/syntax/stdtypes.md
      - 流程控制: doc/syntax/flow.md
    - 面向对象:
      - doc/oop/index.md
      - 作用域与命名空间: doc/oop/scope.md
      - 类与对象: doc/oop/class.md
      - 继承与多态: doc/oop/inheritance.md

plugins:
  # - tags:
  #     tags_file: index/authors.md
  - search:
      lang: zh
  - git-revision-date-localized:
      type: timeago
  - git-committers:
      enabled: !ENV [CI, false]
      repository: BobYue-01/python-guide
      branch: master

markdown_extensions:
  - md_in_html
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - footnotes

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - src/stylesheets/material.css
  - src/stylesheets/extra.css

extra_javascript:
  - src/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - src/javascripts/material.js